name = "Virtual Arsenal Shop System - 3den Editor"
prefix = "TER_VASS"
author = "Terra"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3

files = [
	"mod.cpp",
	"README.md",
	"LICENSE.md"
]

include = [
	"./include"
]

exclude = []
