#define COMPONENT 3den
#include "\z\TER_VASS\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE

#ifdef DEBUG_ENABLED_3den
    #define DEBUG_MODE_FULL
#endif
    #ifdef DEBUG_SETTINGS_OTHER
    #define DEBUG_SETTINGS DEBUG_SETTINGS_3den
#endif

#include "\z\TER_VASS\addons\main\script_macros.hpp"

//--- Display idcs
#define IDC_VASSCARGO_TOOLFILTER 7100
#define IDC_VASSCARGO_LNBCARGO 7101
#define IDC_VASSCARGO_BTNCLEAR 7102
#define IDC_VASSCARGO_BTNMINUS 7103
#define IDC_VASSCARGO_BTNPLUS 7104
#define IDC_VASSCARGO_EDPRICE 7105
#define IDC_VASSCARGO_BTNEXPORT 7106
#define IDC_VASSCARGO_COMBOPRESETS 7107
#define IDC_VASSCARGO_BTNIMPORT 7108
#define IDC_VASSCARGO_TOOLVIEW 7109
#define IDC_VASSCARGO_EDCARGOARRAY 7110
#define IDC_VASSCARGO_STATICLISTBACKGROUND 7111
#define IDC_VASSCARGO_TITLEPRICE 7112
#define IDC_VASSCARGO_GRPCARGOARRAY 7113
#define IDC_VASSCARGO_TXTVALIDATE 7114
#define IDC_VASSCARGO_BTNVALIDATE 7115
